### PR TITLE
pass down usage of isLog

### PR DESCRIPTION
**Pull request by flying-sheep**
isLog is not being used if you use the SeqExpressionSet methods

### CODE REVIEW

**Comment by drisso** [comment]
The `SeqExpressionSet` class always contains counts, so it never makes sense to use `isLog=TRUE`.

But I see that just ignoring `isLog=TRUE` is not good, it should catch it and return an error, I think.

**Comment by drisso** [comment]
Actually, the help file of RUVg et al. already specifies that isLog is ignored when x is a seqExpressionSet, so I'm tempted to leave it this way.

**Comment by flying-sheep** [comment]
Hmm, help file…

I think nobody should be unhelpful if they can be helpful, and silently ignoring things is the most unhelpful behavior programs can have (short of being actual malware)

**Comment by drisso** [comment]
Either way, just passing `isLog` down is not a solution because seqExpressionSet cannot contain logged counts. Hence, the only possible usage is for the user to mistakenly set `isLog=TRUE` when it should be `FALSE`. This (hopefully) will create an error downstream with a non-obvious error message.

I repeat that the correct solution, IMO, is returning an error if x is of class seqExpressionSet and isLog=TRUE.

**Comment by drisso** [comment]
Closing this, and creating new issue.

**Comment by flying-sheep** [comment]
#15, that is

**Pull request closed without merging**
